
// set direction =0 for available node , 1 for related node
export default {
  nodeData: {
    id: 'root',
    topic: 'Mind Elixir #hjhjh#abc #zzz',
    root: true,
    tag: ['cooking','launch'],
    tagActive: '#hjhjh',
    children: [
      {
        topic: 'Mind Elixir #hjhjh#abc #zzz',
        id: 'bd4313fbac0284b',
        // direction: 0,
        // expanded: true,
        tag: ['cooking'],
        customerProfilePicture: '',
        createdBy: 'you',
        nodeLinkCount: 200,
        typeTag: 'relate',
        firstChildTag: true,
        expanded: false,
        children: [{
          topic: 'What is Minde Elixir',
          id: 'bd413fbac40284c',
          // direction: 0,
          // expanded: true,
          tag: ['cooking'],
          customerProfilePicture: '',
          createdBy: 'you',
          nodeLinkCount: 600,
          typeTag: 'relate',
          expanded: true,
          children: [{
            topic: 'What is Mindhhe Elixir',
            id: 'bd4313fbacd40284c',
            // direction: 0,
            // expanded: true,
            tag: ['cooking'],
            customerProfilePicture: '',
            createdBy: 'you',
            nodeLinkCount: 600,
            typeTag: 'relate',
            children: [{
              topic: 'What is Minde Elixir',
              id: 'bd4313fbacdd40284c',
              // direction: 0,
              // expanded: true,
              tag: ['cooking'],
              customerProfilePicture: '',
              createdBy: 'you',
              nodeLinkCount: 600,
              typeTag: 'relate',
              expanded: true,
              
            },
            {
              topic: 'What is Minde Elixir',
              id: 'bd4313fqbac4a0284c',
              // direction: 0,
              // expanded: true,
              tag: ['cooking'],
              customerProfilePicture: '',
              createdBy: 'you',
              nodeLinkCount: 600,
              typeTag: 'relate',
              expanded: true,
            }]
            
          },
          {
            topic: 'What is Minde Elixir',
            id: 'bd4313fqbac40284c',
            // direction: 0,
            // expanded: true,
            tag: ['cooking'],
            customerProfilePicture: '',
            createdBy: 'you',
            nodeLinkCount: 600,
            typeTag: 'relate',
            expanded: true,
          }]
        },
        {
          topic: 'What is Minde Elixir',
          id: 'bd4313fbaac40284c',
          // direction: 0,
          // expanded: true,
          tag: ['cooking'],
          customerProfilePicture: '',
          createdBy: 'you',
          nodeLinkCount: 600,
          typeTag: 'relate',
          expanded: true,
          
        }]
        // background: '#E21818',
      },
      {
        topic: 'What is Minde Elixir',
        id: 'bd4aa313fbac40284b',
        // direction: 1,
        // expanded: true,
        tag: ['cooking'],
        customerProfilePicture: '',
        createdBy: 'GotmikzZ145',
        nodeLinkCount: 200,
        typeTag: 'relate',
        firstChildTag: true,
        expanded: false,
        children: [{
          topic: 'What is Minde Elixir',
          id: 'bdsad4313fbaccs40284c',
          // direction: 0,
          // expanded: true,
          tag: ['cooking'],
          customerProfilePicture: '',
          createdBy: 'you',
          nodeLinkCount: 600,
          typeTag: 'relate',
          background: 'yellow',
          children: [{
            topic: 'What is Minde Elixir',
            id: 'bdsad43d13fbaccs40284c',
            // direction: 0,
            // expanded: true,
            tag: ['cooking'],
            customerProfilePicture: '',
            createdBy: 'you',
            nodeLinkCount: 600,
            typeTag: 'relate',
            background: 'yellow'
          }]
        }]
        // background: '#E21818',
      },
      {
        topic: 'What is Minde Elixir',
        id: 'bd4313fbacdf40284b',
        // direction: 1,
        // expanded: true,
        tag: ['cooking'],
        customerProfilePicture: '',
        createdBy: 'GotmikzZ145',
        nodeLinkCount: 200,
        typeTag: 'relate',
        firstChildTag: true,
        // background: '#E21818',
      },
      {
        topic: 'What is Minde Elixir',
        id: 'bd4313fbac4dsa0284b',
        // direction: 1,
        // expanded: true,
        tag: ['cooking'],
        customerProfilePicture: '',
        createdBy: 'GotmikzZ145',
        nodeLinkCount: 200,
        typeTag: 'relate',
        firstChildTag: true,
        // background: '#E21818',
      },
      {
        topic: 'What is Minde Elixir',
        id: 'bd431ds3fbac40284b',
        // direction: 1,
        // expanded: true,
        tag: ['cooking'],
        customerProfilePicture: '',
        createdBy: 'GotmikzZ145',
        nodeLinkCount: 200,
        typeTag: 'available',
        firstChildTag: true,
        background: 'yellow',
        children: [{
          topic: 'What is Minde Elixir',
          id: 'bd4313fb9ac402dd84c',
          // direction: 0,
          // expanded: true,
          tag: ['cooking'],
          customerProfilePicture: '',
          createdBy: 'you',
          nodeLinkCount: 600,
          typeTag: 'available',
          background: 'yellow',
          children: [{
            topic: 'What is Minde Elixir',
            id: 'bdsad4313fbac40284c',
            // direction: 0,
            // expanded: true,
            tag: ['cooking'],
            customerProfilePicture: '',
            createdBy: 'you',
            nodeLinkCount: 600,
            typeTag: 'available',
            background: 'yellow'
          }]
        }]
        // background: '#E21818',
      }
    ],
    expanded: true,
  },
  linkData: {},
}

